### ISSUE TITLE
Add option to adjust timeout

### ISSUE THREAD

**Issue by gnorbsl** [bcoin-org/breq#3]
If I try to access really large blocks I get a timeout.

Example:
`bcoin-cli --network=testnet tx e191168694de35887e12f6e8ef32b3e4b6212b37bcad0e17a2fe3f8fa11a9f43`

    Error: Request timed out.
    at Timeout.timeout.setTimeout (/home/bcoin/bcoin/node_modules/brq/lib/request.js:369:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)`

**Comment by gnorbsl** [comment]
I tried a 600 seconds timeout with no success, so I assume blocks with 9000 transactions are just unreadable by bcoin

**Comment by thjnhcolag** [comment]
#3

**Comment by bucko13** [comment]
Definitely not unreadable. bcoin still has this block and all its transactions in its db if you're indexing txs and must be able to read them for initial verification (if it didn't, it would be pretty useless as a node since it wouldn't be verifying anything afterwards). 

Where/how did you adjust the timeout?

**Comment by gnorbsl** [comment]
@bucko13 

I adjusted the timeout here:

https://github.com/bcoin-org/brq/blob/master/lib/request.js#L50

I increased it to 600 seconds to test if it does anything at all but I receive a 

    Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by nodech** [comment]
I guess you want `bclient` to accept timeout.
I think this is resolved now: bcoin-org/bcurl/pull/3

**Comment by chjj** [comment]
Think this should be solved now. Closing.
